### ISSUE TITLE
Decide on Metrics

### ISSUE THREAD

**Issue by david3214** [david3214/Team_2_CS_2450-601#10]
Chose general metrics that you intend to make use of and outlined what will be necessary for each metric to be developed.

**Comment by JoshuaJKrueger** [comment]
Honestly metrics don't seem too important for sprint 1, I didn't even see a metrics section in the example sprint 1, and the book mainly only gives ones related to code or company projects, but I tried to come up with a few anyway. These are specific to sprint 1, I figure we can add more later.

- Effort: man hours
- Effort to planning/meeting ratio: not sure if we would really use this but it could be an indicator for if our meetings/planning sessions are effective?
- Artifacts produced: I guess this could be used as an indicator for our progress
- Quality: I'm thinking the quality of our documents, so things like no spelling/grammatical errors etc.. Depending on the attributes we use this could be a bit subjective, however the book gives some subjective examples.

**Comment by vla5qpb7** [comment]
I'm good with those metrics. What else do we need to do before this issue is closed?

**Comment by david3214** [comment]
I like those metrics. I think we basically just need to state that those are going to be our metrics in our write up

**Comment by david3214** [comment]
Chose general metrics that you intend to make use of and outlined what will be necessary for each metric to be developed.
