### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by david3214** [david3214/Team_2_CS_2450-601#108]
UVU requires the following as a condition of the SPR-5 submittal.

* Measure relevant **attributes**
* Use **attributes** to come up with meaningful **metrics**
* Use **metrics** to discover **indicators**
* Use **indicators** to **predict** what the project’s results should have been
* Use **indicators** to make important **corrections** and suggest **improvements**
* Avoid the natural resistance to the use of metrics – Metrics are subject to opinions and require experience to improve quality
* Understand the difference between a Defect and a Bug and **discuss** them accordingly.

**Comment by vla5qpb7** [comment]
estimated to be done by Friday
