### ISSUE TITLE
Maintenance Plan

### ISSUE THREAD

**Issue by david3214** [david3214/Team_2_CS_2450-601#113]
"A complete and functional plan for completing the Maintenance of your product is included and meets the documentation quality of previous Sprint documentation and covers and evaluates the development of your product in clear, well-thought-out, and effective ways. (Refer to the reportdesign.ppx file)"

The [work preview ](https://uvu.instructure.com/courses/546771/pages/spr-5-work-preview?module_item_id=10056608)document has more info towards the bottom on maintenance

**Comment by vla5qpb7** [comment]
estimated to be done by Friday
