### ISSUE TITLE
Time tracking method

### ISSUE THREAD

**Issue by david3214** [david3214/Team_2_CS_2450-601#12]
Developed a time tracking method (e.g. software) that documents estimated and used manhours that will be part of each of the Sprints if the team doesn't wish to use Gantt charts at this stage for tracking time.

**Comment by ComputationalPotato** [comment]
I need everybody's email so that I can invite them. aside from that it is good to go.

**Comment by vla5qpb7** [comment]
My GitHub email is vla5qpb7p@mozmail.com.

**Comment by JoshuaJKrueger** [comment]
jkrew74@gmail.com

**Comment by vla5qpb7** [comment]
Is Everhour a paid app? If so, I suggest we try this instead: https://cattr.app/.

**Comment by vla5qpb7** [comment]
If everyone has Everhour set up, then should we consider this issue closed?

**Comment by JoshuaJKrueger** [comment]
I don't see an invite in the email I sent in nor do I see one in my school email.

**Comment by ComputationalPotato** [comment]
everhour shows your gmail as having already accepted the invite

**Comment by ComputationalPotato** [comment]
everhour can add time that isn't associated with a github task by adding the time in timesheets and just not selecting a task. put what you did in the comments section.

**Comment by JoshuaJKrueger** [comment]
Odd, I wasn't finding it with a search but I went a couple pages back and found it. Unless anyone else has issues I believe we can close this.
