### ISSUE TITLE
V&V Structure Determined

### ISSUE THREAD

**Issue by david3214** [david3214/Team_2_CS_2450-601#14]

**Comment by vla5qpb7** [comment]
I put a first draft of a V&V template in our shared Google Drive. If nobody sees any glaring issues with it, then I'll consider it finished.

**Comment by david3214** [comment]
This reminds me more of the Metric document we will need, but I think we will need a document with outlined V&V tests that we follow when checking our code/Project. Similar to the QA checklist in the Project 6 submission

**Comment by vla5qpb7** [comment]
I thought the V&V and QA checklists where supposed to be separate. Do you think something like the QA checklist is all we need for V&V?

**Comment by vla5qpb7** [comment]
I'll consider the answer to be that we do need two separate checklists, as it seems that way from rereading your comment. I'll have another attempt soon.

**Comment by vla5qpb7** [comment]
I just finished slimming down the QA checklist from 18,852 characters to 5,185 characters (a 72% reduction!). With that done, I believe this issue is ready to be closed.
