### ISSUE TITLE
SPR-2 Pert Chart

### ISSUE THREAD

**Issue by david3214** [david3214/Team_2_CS_2450-601#27]
"Developed SPR-2 Pert Chart with the HLD level CPM and HLD Level Gantt Chart with calendar-based timeboxes." - Rubric
"Pert chart has been updated to determine current CPM based on major WBS components (for Sprint at a minimum)." - Rubric

HLD Level CPM #28 
HLD Level Gantt Chart #29

**Comment by david3214** [comment]
I feel like this applies to project setup, and task management so I'll take a look at it so Zach doesn't have too much

**Comment by david3214** [comment]
I completed the PERT Chart, and put it in google Docs, here is a link to the actual chart, I created it using a tool called Figma. https://www.figma.com/file/n8ipQmlUF5ASJ1ro7mCoS1/CS-2450-Charts?node-id=0%3A1

**Comment by JoshuaJKrueger** [comment]
I think it looks pretty good, I like they you were able to identify the hear of sprint two into the few key tasks and just list the subtasks under them. My concern, however, is that the professor may not pay enough attention to the subtasks and think we didn't include everything. We may want to separate those out into more boxes like in the example provided, although they provide too many in my opinion. If you are not concerned with keeping everything in the subtasks, then I am fine with what you have, just wanted to suggest the possibility.


![Image](https://user-images.githubusercontent.com/24306509/191170025-b3a1a815-e015-45fb-8ac1-102b3501e750.png)
