### ISSUE TITLE
Slide highlights that may apply are recognized as project focus, included and commented where necessary

### ISSUE THREAD

**Issue by david3214** [david3214/Team_2_CS_2450-601#3]
(I'm pretty sure this essentially is all of us to go through the slides and compile our highlights/Notes on what we think is important or what we need to discuss.

**Comment by ComputationalPotato** [comment]
the spr1 document says "Divide chapters 12, 13, and 14 among three or more team members for outlining and highlighting content relative to SPR1 (e.g. choosing one or more models to define your approach to Agile project management.)"
so do i just do slide highlights of our model? it is scrum, right?

**Comment by JoshuaJKrueger** [comment]
Sounds right to me. I believe we are currently using scrum and kanban. Also if you go into the group Gmail account's drive, I made comprehensive slides/notes for chapters 10, 12, 13, and 14. They might come in handy so you don't have to sift through as much.

**Comment by ComputationalPotato** [comment]
So I looked at the slides and the sections on scrum and kanban are useless. the scrum section is just a dictionary of terms, and the kanban section just says the kanban principles then shows a picture of a kanban board.
