### ISSUE TITLE
UML Diagrams for HLD

### ISSUE THREAD

**Issue by david3214** [david3214/Team_2_CS_2450-601#30]
Minimum required UML diagrams are developed that represent the HLD level state (Class, Use case, Sequence, State or Logic Flow (beginning - will be used to develop testing).

**Comment by ComputationalPotato** [comment]
UML Diagram is at https://lucid.app/lucidchart/9bd1da1d-fa65-4cd3-a9e5-1c24708881da/edit?viewport_loc=343%2C343%2C1707%2C823%2C0_0&invitationId=inv_79c4868c-722a-4b56-a051-68c3ce9ee522#

**Comment by ComputationalPotato** [comment]
UML diagram is now in google drive, and will be made in draw.io, due to lucidchart having paywalls.

**Comment by david3214** [comment]
Levels:
Admin has access to everyone's full information
Employee has access to their own full information
Employee has access to everyone's limited information

Create an Actor diagram for these scenarios, defining what information is limited vs full. (IE SSN)
