### ISSUE TITLE
Document Organization

### ISSUE THREAD

**Issue by david3214** [david3214/Team_2_CS_2450-601#34]
"File naming, team naming, cover sheet, division of Sprint into daily (or weekly if you wish) sections, table of contents, page layout, etc."

**Comment by vla5qpb7** [comment]
Question I put on Discord as well:

Are there any file/folder naming requirements that Craig Sharp has said he wants? Like, did he require that our sprint 1 submission was in a folder called "T2-SPR1-CS2450-601_F2"?

**Comment by vla5qpb7** [comment]
I just finished writing a file structure guide, which can be found in the Guides folder. I also made a document template and put it into the Templates folder.

I'll soon mark this issue as closed so long as nobody has any concerns.
