### ISSUE TITLE
V & V completed for SPR-2 document and HLD with respect to requirements spec.

### ISSUE THREAD

**Issue by david3214** [david3214/Team_2_CS_2450-601#51]
"V & V completed for SPR-2 document and HLD with respect to requirements spec."

**Comment by vla5qpb7** [comment]
Make sure requirements spec is addressed in HLD.

**Comment by vla5qpb7** [comment]
V&V for this issue is located at `T2-CS2450-601/Sprint 3/Segments/V&V for HLD`
