### ISSUE TITLE
Main Topics in the table of contents

### ISSUE THREAD

**Issue by david3214** [david3214/Team_2_CS_2450-601#6]
Main topics in a table of Contents.

**Comment by david3214** [comment]
![image](https://user-images.githubusercontent.com/4956867/188978599-6e95d1a9-56e5-40f7-b8cd-32a26a1fd364.png)
Review the sprint 6, and discuss what we want for this

**Comment by JoshuaJKrueger** [comment]
I think their approach is pretty good at least for sprint one. We might consider doing it by team roles in the future, but for know maybe just by the documents/tasks we completed.

**Comment by vla5qpb7** [comment]
I say we mimic what they did for this sprint and adjust it for later sprints as we find what does and doesn't work well.
