### ISSUE TITLE
Survey Sprint Development Procedures

### ISSUE THREAD

**Issue by david3214** [david3214/Team_2_CS_2450-601#8]
Procedures for developing the Sprint have been surveyed  ( (e.g. document versioning, coding standards, scheduling, consistent formatting (indicated by this document, for example), diagramming, documentation tools (burndown, backlog UML Diagramming, WBS, Pert, Gantt, Use Case charting, V&V, etc.) and templates for WBS, Gantt, and Meeting minutes are developed and included.

**Comment by vla5qpb7** [comment]
Here's what I think is done:
- document versioning
- coding standards
- documentation tools
- templates

Here's what I think isn't done:
- scheduling (do we need to set up regular meeting times?)
- consistent formatting (I suggest using MLA as a base)
- diagramming (is someone working on this?)

Has anyone else done a formatting guide? I could slap one together if not.
